wp4/staff/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

from . import views

app_name = "staff"
urlpatterns = [
    url(
        regex=r'^technician-autocomplete/$',
        view=views.TechnicianAutoComplete.as_view(),
        name='technician-autocomplete'
    ),

    url(
        regex=r'^add/$',
        view=views.PersonCreateView.as_view(),
        name='add'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/details/$',
        view=views.PersonDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>[0-9]+)/$',
        view=views.PersonUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^$',
        view=views.PersonListView.as_view(),
        name='list'
    ),
]

wp4/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

# from .perfusion_machine import urls as perfusionmachine_urls
from .health_economics import urls as health_economics_urls
from .followups import urls as followup_urls
from .adverse_event import urls as adverseevent_urls
from .staff import urls as person_urls
# from .staff_person import urls as staffperson_urls
from .locations import urls as locations_urls
from .samples import urls as samples_urls
from .compare import urls as compare_urls
from .administration import urls as administration_urls
from .views import wp4_index


app_name = "wp4"
urlpatterns = [
    url(r'^health-economics/', include(health_economics_urls)),
    url(r'^follow-up/', include(followup_urls)),
    url(r'^adverse-event/', include(adverseevent_urls)),
    url(r'^staff/', include(person_urls)),
    url(r'^location/', include(locations_urls)),
    url(r'^sample/', include(samples_urls)),
    url(r'^compare/', include(compare_urls)),
    url(r'^administration/', include(administration_urls)),

    url(
        regex=r'^$',
        view=wp4_index,
        name='index'
    )
]

wp4/staff/models.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _


class Person(AbstractUser):
    """
    Replacement for original StaffPerson class which was linked to User as a one-to-one via "profile" attribute.

    This represents any person that is a member of staff (medical, administrative, academic, etc) and therefore not
    a patient (see compare.Patient for that). Not all people with records here will be active users of the system

    We'll rely on Django-Reversion to capture changes to records, and thus the audit trail.
    """
    from wp4.locations.models import Hospital

    # Constants to help reference specific staff groups (auth_groups, defined by fixtures)
    PERFUSION_TECHNICIAN = 1  #: Constant for Group ID
    TRANSPLANT_COORDINATOR = 2  #: Constant for Group ID
    RESEARCH_NURSE = 3  #: Constant for Group ID
    NATIONAL_COORDINATOR = 4  #: Constant for Group ID
    CENTRAL_COORDINATOR = 5  #: Constant for Group ID
    STATISTICIAN = 6  #: Constant for Group ID
    SYSTEMS_ADMINISTRATOR = 7  #: Constant for Group ID
    LOCAL_INVESTIGATOR = 8  #: Constant for Group ID
    OTHER_PROJECT_MEMBER = 9  #: Constant for Group ID
    BIOBANK_COORDINATOR = 10  #: Constant for Group ID
    CHIEF_INVESTIGATOR = 11  #: Constant for Group ID
    PRINCIPLE_INVESTIGATOR = 12  #: Constant for Group ID
    CENTRAL_INVESTIGATOR = 13  #: Constant for Group ID
    NATIONAL_INVESTIGATOR = 14  #: Constant for Group ID
    THEATRE_CONTACT = 15  #: Constant for Group ID

    _phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )
    _my_groups = None

    telephone = models.CharField(
        verbose_name=_("SP01 telephone number"),
        validators=[_phone_regex],
        max_length=15,
        blank=True,
        null=True
    )  #: Contents validated against phone_regex ``r'^\+?1?\d{9,15}$'``
    based_at = models.ForeignKey(
        Hospital,
        on_delete=models.PROTECT,
        verbose_name=_("SP02 location"),
        blank=True, null=True,
        help_text="Link to a primary hospital location for the member of staff"
    )

    def has_group(self, group_ids=[]):
        if self._my_groups is None:
            self._my_groups = [g.id for g in self.groups.all()]
        # print("DEBUG: I am {2}, and my_group_ids={0} and group_ids={1} ({3})".format(
        #     my_group_ids, group_ids, self.get_full_name(), type(group_ids))
        # )
        if type(group_ids) in (list, tuple):
            for group in group_ids:
                if group in self._my_groups:
                    return True
        else:
            if group_ids in self._my_groups:
                return True
        # print("DEBUG: has_group returning False")
        return False

    def _is_administrator(self):
        """
        Checks for membership of an admin group
        :return:
        """
        administrator_groups = (self.NATIONAL_COORDINATOR, self.CENTRAL_COORDINATOR, self.SYSTEMS_ADMINISTRATOR,
                                self.BIOBANK_COORDINATOR, self.CHIEF_INVESTIGATOR, self.PRINCIPLE_INVESTIGATOR,
                                self.NATIONAL_INVESTIGATOR, self.CENTRAL_INVESTIGATOR, self.STATISTICIAN,)
        if self.has_group(administrator_groups):
            return True
        elif self.has_group(self.CENTRAL_INVESTIGATOR) and settings.DEBUG is True:
            # Add a pass through for Ina when on the test server as per Issue #249
            return True
        return False

    is_administrator = cached_property(_is_administrator, name='is_administrator')

    class Meta:
        verbose_name = _('SPm1 person')
        verbose_name_plural = _('SPm2 people')
        ordering = ['id']
        permissions = (
            ("single_person", "Can only view their own person record"),
        )

    def get_absolute_url(self):
        return reverse("wp4:staff:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.get_full_name()

wp4/staff/forms.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

# import re

from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML
from crispy_forms.bootstrap import InlineCheckboxes

from .models import Person


class PersonForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_tag = False
    helper.html5_required = True
    helper.layout = Layout(
        Div(
            Div(
                'is_active',
                'first_name',
                'last_name',
                'email',
                'telephone',
                css_class="col-md-6", style="margin-top: 10px;"
            ),
            Div(
                'based_at',
                InlineCheckboxes('groups'),
                HTML("""
                   <a href="{% url 'password_change' %}" class="btn btn-default">Change User Password</a> 
                   NB: This requires the user's existing password to be used.
                """),
                css_class="col-md-6", style="margin-top: 10px;"
            ),
            css_class="row"
        )
    )

    def __init__(self, data=None, *args, **kwargs):
        super(PersonForm, self).__init__(data=data, *args, **kwargs)
        self.render_required_fields = True

    class Meta:
        model = Person
        fields = ('is_active', 'first_name', 'last_name', 'telephone', 'email', 'based_at', 'groups')


class PersonAjaxForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_tag = False
    helper.html5_required = True
    helper.layout = Layout(
        'first_name',
        'last_name',
        'based_at',
        'telephone',
        'email',
    )

    def __init__(self, data=None, *args, **kwargs):
        # # Special intercept and clean of data to account for jQuery.serialise data mangling of lists
        # # TODO: Check that this is needed or working... jobs having been superseded by Groups
        # if data is not None:
        #     jquery_serialise_list_pattern = re.compile("^\[(\d+,?\s?)+\]$")
        #     if isinstance(data['groups'], type(u'')) and jquery_serialise_list_pattern.match(data['groups']):
        #         data = data.copy()  # make it mutable
        #         data['groups'] = [int(i) for i in data['groups'][1:-1].split(",")]
        super(PersonAjaxForm, self).__init__(data=data, *args, **kwargs)
        self.render_required_fields = True

    # TODO: Implement form save so that groups are correctly added

    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'telephone', 'email', 'based_at')

wp4/staff/views.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.models import Group
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from braces.views import LoginRequiredMixin, PermissionRequiredMixin, OrderableListMixin, MultiplePermissionsRequiredMixin
from dal import autocomplete

from wp4.theme.layout import AjaxReturnIDMixin
from .models import Person
from .forms import PersonForm, PersonAjaxForm
from .utils import generate_username


class TechnicianAutoComplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Person.objects.none()

        qs = Person.objects.filter(groups__in=[Person.PERFUSION_TECHNICIAN])

        if self.q:
            qs = qs.filter(Q(first_name__icontains=self.q) | Q(last_name__icontains=self.q))

        return qs


# ============================================  MIXINS
class AjaxListSearchMixin(object):
    def get_queryset(self):
        queryset = super(AjaxListSearchMixin, self).get_queryset()
        if self.request.is_ajax():
            queryset = queryset.order_by('first_name')

        # If a q value is set, filter based on groups
        q = self.request.GET.get("q")
        if q and q.isdigit():
            return queryset.filter(groups__id__in=[int(q)])
        return queryset

    def get_template_names(self):
        # print("DEBUG: get_template_names():is_ajax? %s" % self.request.is_ajax())
        if self.request.is_ajax():
            self.template_name = "staff/person_list.ajax.html"
        return super(AjaxListSearchMixin, self).get_template_names()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AjaxListSearchMixin, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the groups
        context['group_list'] = Group.objects.all()
        return context


class AjaxFormMixin(object):
    form_class = PersonForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.username = generate_username(self.object)
        self.object.save()
        form.save_m2m()

        if self.request.is_ajax():
            return self.render_to_response(self.get_context_data(form=form))
        else:
            return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        print("DEBUG: form_invalid() errors: %s" % form.errors)
        error_count = len(form.errors)
        error_pluralise = "" if error_count == 1 else "s"
        messages.error(
            self.request,
            '<strong>Form was NOT saved</strong>, please correct the %d error%s below' %
            (error_count, error_pluralise)
        )
        return super(AjaxFormMixin, self).form_invalid(form)

    def get_form(self, form_class=None):
        if not self.request.user.is_administrator:
            form_class = PersonAjaxForm  # Stop non admins from changing groups
        form = super(AjaxFormMixin, self).get_form(form_class)

        # Both post() and get() call get_form() first, so this is best place to intercept ajax changes
        if self.request.is_ajax():
            form = super(AjaxFormMixin, self).get_form(PersonAjaxForm)
            # form.fields['groups'].widget = forms.HiddenInput()
            self.template_name = "staff/person_form.ajax.html"
        return form


# ============================================  CBVs
class PersonListView(AjaxReturnIDMixin, AjaxListSearchMixin,
                     LoginRequiredMixin, MultiplePermissionsRequiredMixin,
                     OrderableListMixin, ListView):
    model = Person
    permissions = {
        "all": (),
        "any": ("staff.change_person", "staff.single_person"),
    }
    ordering = ['first_name']
    paginate_by = 50
    paginate_orphans = 5
    orderable_columns = ("first_name", "last_name", "email", "telephone", "based_at")
    orderable_columns_default = "first_name"

    def get_paginate_by(self, queryset):
        """
        Get the number of items to paginate by, or ``None`` for no pagination.
        """
        if self.request.is_ajax():
            # Don't paginate for ajax listings
            return None

        return self.paginate_by


class PersonDetailView(AjaxReturnIDMixin, LoginRequiredMixin, MultiplePermissionsRequiredMixin, DetailView):
    model = Person
    permissions = {
        "all": (),
        "any": ("staff.change_person", "staff.single_person"),
    }


class PersonCreateView(AjaxReturnIDMixin, AjaxFormMixin,
                       LoginRequiredMixin, MultiplePermissionsRequiredMixin,
                       CreateView):
    model = Person
    permissions = {
        "all": ("staff.add_person", ),
        "any": (),
    }


class PersonUpdateView(AjaxReturnIDMixin, AjaxFormMixin,
                       LoginRequiredMixin, MultiplePermissionsRequiredMixin,
                       UpdateView):
    model = Person
    permissions = {
        "all": ("staff.change_person", ),
        "any": (),
    }

wp4/theme/templates/staff/person_detail.html
{% extends "base_site.html" %}
{% load theme_tags %}

{% block page_title %}Staff{% endblock %}
{% block page_header %}Staff{% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'wp4:staff:list' %}">Staff</a></li>
    <li class="active"><i class="glyphicon glyphicon-eye-open"></i> {{ person.get_full_name }}</li>
{% endblock %}

{% block content %}
    <h2>
        <a href="{% url 'wp4:staff:update' person.id %}" class="btn btn-primary" title="Edit this Person">
            <i class="glyphicon glyphicon-edit"></i> {{ person.id }}
        </a> {{ person.get_full_name }}
        {% if request.user.is_staff %}
            <small>
            <a href="{% url 'admin:staff_person_change' person.id %}"><i class="glyphicon glyphicon-briefcase"></i></a>
            </small>
        {% endif %}
    </h2>
    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>First Name</dt>
                <dd>{{ person.first_name }}</dd>
                <dt>Last Name</dt>
                <dd>{{ person.last_name }}</dd>
                <dt>Telephone</dt>
                <dd>{{ person.telephone|default:"Unknown" }}</dd>
                <dt>Email</dt>
                <dd>{{ person.email|default:"Unknown" }}</dd>
                <dt>Based At</dt>
                <dd>{{ person.based_at|default:"Unknown" }}</dd>
            </dl>
        </div>
        <div class="col-md-6">

            <dl class="dl-horizontal">
                <dt>ID</dt>
                <dd>{{ person.id }}</dd>
                <dt>Username</dt>
                <dd>{{ person.username }}</dd>
                <dt>Is Active?</dt>
                <dd class="{% if not person.is_active %}bg-danger{% endif %}">
                    {{ person.is_active|yesno|capfirst }}
                </dd>
                {% if user.is_staff %}
                <dt>Is Staff?</dt>
                <dd>{{ person.is_staff|yesno|capfirst }}</dd>
                <dt>Is Superuser?</dt>
                <dd>{{ person.is_superuser|yesno|capfirst }}</dd>
                {% endif %}
                <dt>Is Administrator</dt>
                <dd>{{ person.is_administrator|yesno|capfirst }}</dd>
                <dt>Roles</dt>
                <dd>
                {% for job in person.groups.all %}
                {{ job.name }}<br>
                {% endfor %}
                </dd>
            </dl>
        </div>
    </div>
{% endblock %}

wp4/theme/templates/staff/person_form.ajax.html
{% load l10n i18n %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% if form.is_valid %}
    <script type="text/javascript">
        selectAndCloseForeignKeyModal('{{ return_id }}', {{ form.instance.pk }}, '{{ form.instance.full_name }}');
    </script>
{% else %}

    {% include "includes/messages.html" %}

    <form class="" id="person_form">
        {% if form.non_field_errors %}
            <div class="col-md-12" style="margin-top: 10px;">
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        {% crispy form %}
        <input type="hidden" name="return_id" value="{{ return_id }}">
    </form>

    <script type="text/javascript">
        // Initialise the modal
        $('#myModalLabel').text("Manage Staff");
        $('#modal-action-button').text("Save and Use").removeClass("hidden");
        $('#modal-action-button').attr("onClick", "saveForeignKeyModal();");

        function saveForeignKeyModal() {
            $.ajax({
                url: getBaseURL() + "wp4/staff/{{ form.instance.pk|default:"add" }}/",
                type: "POST",  // This is comply with CBV premise that POST saves forms
                data: $("#person_form").serializeArray(),
                success: function (htmlContent) {
                    $('#modal-content').html(htmlContent);
                },
                error: function (xhr, errmsg, err) {
                    // Show an error
                    alert("ERROR: Problem when communicating with server.\n\n" +
                            "Error message: (" + xhr.status + ") " + errmsg + "\n\n" +
                            "Please let the admin team know you've seen this error.");
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                    $('#myModal').modal('hide');
                }
            });
        }
    </script>
{% endif %}

wp4/theme/templates/staff/person_form.html
{% extends "base_site.html" %}
{% load l10n i18n %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block page_title %}Staff{% endblock %}
{% block page_header %}Staff{% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'wp4:staff:list' %}">Staff</a></li>
    <li class="active"><i class="glyphicon glyphicon-edit"></i> {{ person.get_full_name }}</li>
{% endblock %}

{% block content %}
    <form method="post" class="" id="person_form">
        {% if form.non_field_errors %}
            <div class="col-md-12" style="margin-top: 10px;">
                {% for error in form.non_field_errors %}
                    <p class="alert alert-danger">{{ error }}</p>
                {% endfor %}
            </div>
        {% endif %}
        {% crispy form %}
    </form>

{% endblock %}


{% block footer_nav %}
    <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-right">
                <input type="button" class="btn btn-primary navbar-btn" value="Save" id="nav_button_save"/>
            </div>
        </div>
    </nav>
{% endblock %}


{% block footer_extra_scripts %}
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function (event) {
            // Navbar bottom actions
            $('footer').addClass('navbar_spacing');
            $('#nav_button_save').on('click', function () {
                $('#person_form').submit();
            });
        });
    </script>
{% endblock %}

wp4/theme/templates/staff/person_list.ajax.html
{% if person_list %}
    <ul class="list-group">
        {% for person in person_list %}
            <a href="#"
               onclick="selectAndCloseForeignKeyModal('{{ return_id }}', {{ person.id }}, '{{ person.get_full_name }}');"
               class="list-group-item"><i class="glyphicon glyphicon-save"></i> <strong>{{ person.get_full_name }}</strong> ({{ person.based_at.name|default:"Unknown location" }})</a>
        {% endfor %}
    </ul>
{% else %}
    <p>No people are available.</p>
{% endif %}
<p><a href="#" onclick="changeForeignKeyModalToAdd('{{ return_id }}')" class="btn btn-primary"><i
        class="glyphicon glyphicon-plus"></i> Add
    Person</a></p>


    <script type="text/javascript">
        // Initialise the modal
        $('#myModalLabel').text("Manage Staff");
    </script>

wp4/theme/templates/staff/person_list.html
{% extends "base_site.html" %}
{% load theme_tags %}

{% block page_title %}Staff{% endblock %}
{% block page_header %}Staff {% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li class="active">Staff</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
    {% if person_list %}
        {% include 'includes/paginator.html' %}
        <table class="table table-responsive table-striped table-condensed">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th title="First Name">
                        First {% include 'includes/sort_column.html' with sort_by_field='first_name' default_sort=True %}
                    </th>
                    <th title="Last Name">
                        Last {% include 'includes/sort_column.html' with sort_by_field='last_name' %}
                    </th>
                    <th title="Telephone">
                        Tel {% include 'includes/sort_column.html' with sort_by_field='telephone' %}
                    </th>
                    <th title="Email">
                        Email {% include 'includes/sort_column.html' with sort_by_field='email' %}
                    </th>
                    <th title="Based at Hospital">
                        Base {% include 'includes/sort_column.html' with sort_by_field='based_at' %}
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for person in person_list %}
                <tr>
                    <td>
                        {% if perms.staff.change_person %}
                            <div class="btn-group" role="group">
                        <a href="{% url 'wp4:staff:detail' person.id %}" class="btn btn-xs btn-default"><i
                            class="glyphicon glyphicon-eye-open"></i> {{ person.id }}</a>
                        <a href="{% url 'wp4:staff:update' person.id %}" class="btn btn-xs btn-primary"><i
                            class="glyphicon glyphicon-edit"></i></a>
                            </div>
                        {% elif perms.staff.view_person %}
                        <a href="{% url 'wp4:staff:detail' person.id %}" class="btn btn-xs btn-default"><i
                            class="glyphicon glyphicon-eye-open"></i> {{ person.id }}</a>
                        {% else %}
                            {{ person.id }}
                        {% endif %}
                    </td>
                    <td>{{ person.first_name }}</td>
                    <td>{{ person.last_name }}</td>
                    <td>{{ person.telephone }}</td>
                    <td>{{ person.email }}</td>
                    <td>{{ person.based_at.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'includes/paginator.html' %}

        {% else %}
            <p>No people are available.</p>
        {% endif %}
    </div>
    <div class="col-md-3">
        <h3>Filters</h3>
        <ul class="list-group">
            <li class="list-group-item">
                <h4 class="list-group-item-heading">Roles</h4>
            </li>
            <a class="list-group-item {% if request.GET.q == none %}active{% endif %}"
               href="?{% query_transform request page=1 q=None %}">All</a>
            {% for role in  group_list %}
                <a class="list-group-item {% if request.GET.q == role.id|lower %}active{% endif %}"
                   href="?{% query_transform request page=1 q=role.id %}">
                    {{ role.name }}
                    <span class="badge">{{ role.user_set.count }}</span>
                </a>
            {% endfor %}
        </ul>
    </div>
</div>

{% if perms.staff.add_person %}
<p><a href="{% url "wp4:staff:add" %}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Add Person</a></p>
{% endif %}
{% endblock %}