wp4/samples/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


app_name = "samples"
urlpatterns = [
    url(
        regex=r'^$',
        view=views.index,
        name='index'
    ),

    # ======================  Events
    url(
        regex=r'^event/(?P<pk>[0-9]+)/details/$$',
        view=views.EventDetailView.as_view(),
        name='event_detail'
    ),
    url(
        regex=r'^event/(?P<pk>[0-9]+)/$$',
        view=views.EventUpdateView.as_view(),
        name='event_update'
    ),
    url(
        regex=r'^event/$',
        view=views.EventListView.as_view(),
        name='event_list'
    ),

    # ======================  Donors

    url(
        regex=r'^donor/(?P<pk>[0-9]+)/details/$$',
        view=views.DonorSamplesDetailView.as_view(),
        name='donor_detail'
    ),

    url(
        regex=r'^donor/$',
        view=views.DonorSamplesListView.as_view(),
        name='donor_list'
    ),

    # ======================  Organs

    url(
        regex=r'^organ/(?P<pk>[0-9]+)/details/$$',
        view=views.OrganSamplesDetailView.as_view(),
        name='organ_detail'
    ),

    url(
        regex=r'^organ/$',
        view=views.OrganSamplesListView.as_view(),
        name='organ_list'
    ),

    # ======================  Recipients

    url(
        regex=r'^recipient/(?P<pk>[0-9]+)/details/$$',
        view=views.RecipientSamplesDetailView.as_view(),
        name='recipient_detail'
    ),

    url(
        regex=r'^recipient/$',
        view=views.RecipientSamplesListView.as_view(),
        name='recipient_list'
    ),
]

wp4/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

# from .perfusion_machine import urls as perfusionmachine_urls
from .health_economics import urls as health_economics_urls
from .followups import urls as followup_urls
from .adverse_event import urls as adverseevent_urls
from .staff import urls as person_urls
# from .staff_person import urls as staffperson_urls
from .locations import urls as locations_urls
from .samples import urls as samples_urls
from .compare import urls as compare_urls
from .administration import urls as administration_urls
from .views import wp4_index


app_name = "wp4"
urlpatterns = [
    url(r'^health-economics/', include(health_economics_urls)),
    url(r'^follow-up/', include(followup_urls)),
    url(r'^adverse-event/', include(adverseevent_urls)),
    url(r'^staff/', include(person_urls)),
    url(r'^location/', include(locations_urls)),
    url(r'^sample/', include(samples_urls)),
    url(r'^compare/', include(compare_urls)),
    url(r'^administration/', include(administration_urls)),

    url(
        regex=r'^$',
        view=wp4_index,
        name='index'
    )
]

wp4/samples/models.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.validators import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


from wp4.compare.models.core import AuditControlModelBase
from wp4.compare.models import Patient, Organ
from .managers import EventModelForUserManager, SampleFromOrganModelForUserManager, SampleFromPersonModelForUserManager


class BarCodeMixin(models.Model):
    """
    Extends with a barcode field
    """
    barcode = models.CharField(verbose_name=_("BC01 barcode number"), max_length=20, blank=True, db_index=True)

    class Meta:
        abstract = True

    def __str__(self):
        return "{0}: {1}".format(self.id, self.barcode)


class DeviationMixin(models.Model):
    """
    In place of Deviation records on a worksheet, we have a way of tracking them per sample.
    Also holds the meta question of whether this specific sample was actually taken or not.
    """
    collected = models.NullBooleanField(verbose_name=_("DM01 sample collected?"), blank=True)
    notes = models.TextField(verbose_name=_("DM02 notes"), blank=True, help_text="Deviation record")

    class Meta:
        abstract = True


class WP7Record(BarCodeMixin):
    """
    Based on an export from the WP7 Database. A record in this table means a sample exists on file in the Biobank
    """
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey()

    box_number = models.CharField(max_length=20, null=True, blank=True)
    position_in_box = models.CharField(max_length=3, null=True, blank=True)

    class Meta:
        verbose_name = 'WP7 Record'
        verbose_name_plural = 'WP7 Records'


class Event(AuditControlModelBase):
    """
    A Sample Event is a timepoint and process where a specific type of biological sample was extracted
    from a person. This even can validate whether enough biological samples were taken (e.g. a blood
    sample results in two separate containers; whereas a perfusate sample has only one), and acts as the
    link between a Worksheet and the various Sample types
    """
    TYPE_BLOOD = 1  #: Constant for TYPE_CHOICES
    TYPE_URINE = 2  #: Constant for TYPE_CHOICES
    TYPE_PERFUSATE = 3  #: Constant for TYPE_CHOICES
    TYPE_TISSUE = 4  #: Constant for TYPE_CHOICES
    TYPE_CHOICES = (
        (TYPE_BLOOD, _("EVc01 Blood")),
        (TYPE_URINE, _("EVc02 Urine")),
        (TYPE_PERFUSATE, _("EVc03 Perfusate")),
        (TYPE_TISSUE, _("EVc04 Tissue")),
    )  #: Limit of choices for Event type data
    NAME_DONOR_BLOOD1 = 1  #: Constant for NAME_CHOICES
    NAME_DONOR_URINE1 = 2  #: Constant for NAME_CHOICES
    NAME_DONOR_URINE2 = 3  #: Constant for NAME_CHOICES
    NAME_ORGAN_PERFUSATE1 = 4  #: Constant for NAME_CHOICES
    NAME_ORGAN_PERFUSATE2 = 5  #: Constant for NAME_CHOICES
    NAME_ORGAN_PERFUSATE3 = 6  #: Constant for NAME_CHOICES
    NAME_ORGAN_TISSUE = 7  #: Constant for NAME_CHOICES
    NAME_RECIPIENT_BLOOD1 = 8  #: Constant for NAME_CHOICES
    NAME_RECIPIENT_BLOOD2 = 9  #: Constant for NAME_CHOICES
    NAME_CHOICES = (
        (NAME_DONOR_BLOOD1, _("EVc05 donor blood 1")),
        (NAME_DONOR_URINE1, _("EVc06 donor urine 1")),
        (NAME_DONOR_URINE2, _("EVc07 donor urine 2")),
        (NAME_ORGAN_PERFUSATE1, _("EVc08 organ perfusate 1")),
        (NAME_ORGAN_PERFUSATE2, _("EVc09 organ perfusate 2")),
        (NAME_ORGAN_PERFUSATE3, _("EVc10 organ perfusate 3")),
        (NAME_ORGAN_TISSUE, _("EVc11 organ tissue 1")),
        (NAME_RECIPIENT_BLOOD1, _("EVc12 recipient blood 1")),
        (NAME_RECIPIENT_BLOOD2, _("EVc13 recipient blood 2")),
    )  #: Limit of choices for Event name data

    type = models.PositiveSmallIntegerField(_("EV01 sample type"), choices=TYPE_CHOICES)
    name = models.PositiveSmallIntegerField(_("EV03 sample process name"), choices=NAME_CHOICES)
    taken_at = models.DateTimeField(verbose_name=_("EV02 date and time taken"), null=True, blank=True)

    objects = EventModelForUserManager()

    class Meta:
        ordering = ['type', 'name']
        verbose_name = _('EVm1 sample event')
        verbose_name_plural = _('EVm2 sample events')

    def clean(self):
        """
        If type is...

        * BLOOD - check for two different types of BloodSample
        * URINE - check for one type of UrineSample
        * PERFUSATE - check for one type of PerfusateSample
        * TISSUE - check for two different types of TissueSample

        ... and that a suitable Event name was chosen, and that taken_at value  is not in the future.

        :return: None
        """
        if self.type == Event.TYPE_BLOOD:
            sample_set = self.bloodsample_set.all()
            count = len(sample_set)
            if count > 0 and count != 2:
                raise ValidationError(_("EVv01 this event should have two blood sample records"))
            if sample_set[0].blood_type == sample_set[1].blood_type:
                raise ValidationError(_("EVv06 the blood samples must not have matching types"))
            if self.name not in (Event.NAME_DONOR_BLOOD1, Event.NAME_RECIPIENT_BLOOD1, Event.NAME_RECIPIENT_BLOOD2):
                raise ValidationError(_("EVv08 invalid name selected (please select a blood related name)"))
        if self.type == Event.TYPE_URINE:
            count = len(self.urinesample_set.all())
            if count > 0 and count != 1:
                raise ValidationError(_("EVv02 this event should have one urine sample record"))
            if self.name not in (Event.NAME_DONOR_URINE1, Event.NAME_DONOR_URINE2):
                raise ValidationError(_("EVv09 invalid name selected (please select a urine related name)"))
        if self.type == Event.TYPE_PERFUSATE:
            count = len(self.perfusatesample_set.all())
            if count > 0 and count != 1:
                raise ValidationError(_("EVv03 this event should have one perfusate sample record"))
            if self.name not in (Event.NAME_ORGAN_PERFUSATE1, Event.NAME_ORGAN_PERFUSATE2, Event.NAME_ORGAN_PERFUSATE3):
                raise ValidationError(_("EVv10 invalid name selected (please select a perfusate related name)"))
        if self.type == Event.TYPE_TISSUE:
            sample_set = self.tissuesample_set.all()
            count = len(sample_set)
            if count > 0 and count != 2:
                raise ValidationError(_("EVv04 this event should have two tissue sample records"))
            if sample_set[0].tissue_type and sample_set[1].tissue_type and sample_set[0].tissue_type == sample_set[1].tissue_type:
                raise ValidationError(_("EVv07 the tissue samples must not have matching types"))
            if self.name != Event.NAME_ORGAN_TISSUE:
                raise ValidationError(_("EVv11 invalid name selected (please select a tissue related name)"))
        if self.taken_at:
            if self.taken_at > timezone.now():
                raise ValidationError(_("EVv05 Time travel detected! Taken at date and time is in the future!"))

    def __str__(self):
        return "{0}".format(self.get_name_display())

    def get_absolute_url(self):
        return reverse("wp4:samples:event_detail", kwargs={"pk": self.pk})


class BloodSample(AuditControlModelBase, BarCodeMixin, DeviationMixin):
    """
    Sample class type for Blood samples.

    Also contains a helper (repeated, but direct) link to the Patient this sample was from (mainly
    to aide reverse sample look ups from Patient)
    """
    SAMPLE_SST = 1  #: Constant for SAMPLE_CHOICES
    SAMPLE_EDSA = 2  #: Constant for SAMPLE_CHOICES
    SAMPLE_CHOICES = (
        (SAMPLE_SST, _("BSc01 Blood SST")),
        (SAMPLE_EDSA, _("BSc02 Blood EDSA"))
    )  #: Limit of choices for BloodSample blood_type

    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        limit_choices_to={'type': Event.TYPE_BLOOD},
        help_text="Link to an event of type Blood"
    )
    blood_type = models.PositiveSmallIntegerField(verbose_name=_("BS02 blood sample type"), choices=SAMPLE_CHOICES)
    person = models.ForeignKey(Patient, on_delete=models.PROTECT, verbose_name=_("BS03 sample from"))
    centrifuged_at = models.DateTimeField(verbose_name=_("BS01 centrifuged at"), null=True, blank=True)
    wp7_location = GenericRelation(WP7Record, blank=True)

    objects = SampleFromPersonModelForUserManager()

    class Meta:
        ordering = ['person', 'event__taken_at']
        verbose_name = _('BSm1 blood sample')
        verbose_name_plural = _('BSm2 blood samples')

    def clean(self):
        """
        If sample is marked as collected, confirm taken_at date is present, otherwise that deviation
        notes have been recorded.

        Ensure that centrifuged_at datetime is not in the future, and that it occured after taken_at datetime

        :return: None
        """
        if self.collected is not None:
            if not self.collected and self.notes == "":
                raise ValidationError(_("BSv01 you must enter some notes about why this sample was not collected"))
            if self.collected and not self.event.taken_at:
                raise ValidationError(_("BSv04 Please record the time the sample was taken"))

        if self.centrifuged_at:
            if self.centrifuged_at > timezone.now():
                raise ValidationError(_("BSv02 Time travel detected! Centrifuged at date and time is in the future!"))
            if self.event.taken_at:
                if self.centrifuged_at < self.event.taken_at:

wp4/theme/templates/samples/donor_detail.html
{% extends "base_site.html" %}
{% load l10n i18n %}
{% load theme_tags %}

{% block page_title %}Samples{% endblock %}
{% block page_header %}Samples - Donor
    <small>Trial ID #{{ donor.trial_id }}</small>{% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'wp4:index' %}">WP4: Compare</a></li>
    <li><a href="{% url 'wp4:samples:index' %}">Samples</a></li>
    <li><a href="{% url 'wp4:samples:donor_list' %}">Donor Samples</a></li>
    <li class="active">View Samples for #{{ donor.trial_id }}</li>
{% endblock %}


{% block content %}

    {% for sample in donor.person.bloodsample_set.all %}
        {% if forloop.counter0|divisibleby:"2" %}
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-primary }}">
                <div class="panel-heading">
                    <h3 class="panel-title">Event #{{ sample.event.id }}</h3>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'type' %}:</strong> {{ sample.event.get_type_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'name' %}:</strong> {{ sample.event.get_name_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'taken_at' %}:</strong> {{ sample.event.taken_at }}
                    </li>
                </ul>
            </div>
            {% if perms.samples.change_event %}
                <p><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-lg"><i
                        title="edit" class="glyphicon glyphicon-edit"></i> Edit Event #{{ sample.event.pk }}</a></p>
            {% endif %}
        </div>
        <div class="col-md-4">
            <div class="panel panel-default }}">
                {% if user.is_administrator %}
                <div class="panel-heading">
                    <h3 class="panel-title">Sample #{{ sample.id }}</h3>
                </div>
                {% endif %}
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'blood_type' %}:</strong> {{ sample.get_blood_type_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'barcode' %}:</strong>
                        {{ sample.barcode|default:"Not recorded" }}
                    </li>
                    <li class="list-group-item
                            {{ sample.collected|yesno:"list-group-item-success,list-group-item-danger,list-group-item-warning" }}">
                        <strong>{% get_verbose_field_name sample 'collected' %}</strong><br>&nbsp;
                        <span class="badge">{{ sample.collected|yesno }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'centrifuged_at' %}:</strong>
                        {{ sample.centrifuged_at|default:"Not recorded" }}
                    </li>
                </ul>
                <div class="panel-body">
                    <h4>{% get_verbose_field_name sample 'notes' %}</h4>
                    <div>{{ sample.notes }}</div>
                </div>
            </div>
        </div>
        {% else %}

        <div class="col-md-4">
            <div class="panel panel-default }}">
                {% if user.is_administrator %}
                <div class="panel-heading">
                    <h3 class="panel-title">Sample #{{ sample.id }}</h3>
                </div>
                {% endif %}
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'blood_type' %}:</strong> {{ sample.get_blood_type_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'barcode' %}:</strong>
                        {{ sample.barcode|default:"Not recorded" }}
                    </li>
                    <li class="list-group-item
                            {{ sample.collected|yesno:"list-group-item-success,list-group-item-danger,list-group-item-warning" }}">
                        <strong>{% get_verbose_field_name sample 'collected' %}</strong><br>&nbsp;
                        <span class="badge">{{ sample.collected|yesno }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'centrifuged_at' %}:</strong>
                        {{ sample.centrifuged_at|default:"Not recorded" }}
                    </li>
                </ul>
                <div class="panel-body">
                    <h4>{% get_verbose_field_name sample 'notes' %}</h4>
                    <div>{{ sample.notes }}</div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if not forloop.counter0|divisibleby:"2" %}
    </div>
        {% endif %}
    {% empty %}
        <p>No Blood Samples recorded for this Donor</p>
    {% endfor %}

    {% for sample in donor.person.urinesample_set.all %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary }}">
                <div class="panel-heading">
                    <h3 class="panel-title">Event #{{ sample.event.id }}</h3>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'type' %}:</strong> {{ sample.event.get_type_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'name' %}:</strong> {{ sample.event.get_name_display }}
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample.event 'taken_at' %}:</strong> {{ sample.event.taken_at }}
                    </li>
                </ul>
            </div>
            {% if perms.samples.change_event %}
                <p><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-lg"><i
                        title="edit" class="glyphicon glyphicon-edit"></i> Edit Event #{{ sample.event.pk }}</a></p>
            {% endif %}
        </div>
        <div class="col-md-6">
            <div class="panel panel-default }}">
                {% if user.is_administrator %}
                <div class="panel-heading">
                    <h3 class="panel-title">Sample #{{ sample.id }}</h3>
                </div>
                {% endif %}
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'barcode' %}:</strong>
                        {{ sample.barcode|default:"Not recorded" }}
                    </li>
                    <li class="list-group-item
                            {{ sample.collected|yesno:"list-group-item-success,list-group-item-danger,list-group-item-warning" }}">
                        <strong>{% get_verbose_field_name sample 'collected' %}</strong><br>&nbsp;
                        <span class="badge">{{ sample.collected|yesno }}</span>
                    </li>
                    <li class="list-group-item">
                        <strong>{% get_verbose_field_name sample 'centrifuged_at' %}:</strong>
                        {{ sample.centrifuged_at|default:"Not recorded" }}
                    </li>
                </ul>
                <div class="panel-body">
                    <h4>{% get_verbose_field_name sample 'notes' %}</h4>
                    <div>{{ sample.notes }}</div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
        <p>No Urine Samples recorded for this Donor</p>
    {% endfor %}

{% endblock %}

wp4/theme/templates/samples/donor_list.html
{% extends "base_site.html" %}
{% load l10n i18n theme_tags %}

{% block page_title %}Samples{% endblock %}
{% block page_header %}Samples - Donors{% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'wp4:index' %}">WP4: Compare</a></li>
    <li><a href="{% url 'wp4:samples:index' %}">Samples</a></li>
    <li class="active">Donor Samples</li>
{% endblock %}

{% block content %}
    {% if donor_list %}
        {% include 'includes/paginator.html' %}
        <table class="table table-responsive table-condensed">
            <thead>
            <tr>
                <th>Trial ID {% include 'includes/sort_column.html' with sort_by_field='trial_id' %}</th>
                <th>Name</th>
                <th>Taken at</th>
                <th>Barcode</th>
                <th>Collected</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for donor in donor_list %}
                <tr>
                {% with blood_count=donor.person.bloodsample_set.all.count urine_count=donor.person.urinesample_set.all.count %}
                    <td rowspan="{{ blood_count|add:urine_count }}">

                        <strong>{{ donor.trial_id }}</strong><br>
                        {% if perms.samples.change_event %}
                            <a href="{% url 'wp4:samples:donor_detail' pk=donor.pk %}" class="btn btn-default btn-xs"><i
                                    title="edit" class="glyphicon glyphicon-eye-open"></i></a>
{#                            <a href="{% url 'wp4:samples:event_update' pk=event.pk %}" class="btn btn-primary btn-xs"><i#}
{#                                    title="edit" class="glyphicon glyphicon-edit"></i> {{ donor.id }}</a>#}
                        {% elif perms.samples.view_event %}
                            <a href="{% url 'wp4:samples:donor_detail' pk=donor.pk %}" class="btn btn-default btn-xs"><i
                                    title="edit" class="glyphicon glyphicon-eye-open"></i> {{ donor.id }}</a>
                        {% endif %}
                    </td>
                {% if blood_count == 0 and urine_count == 0 %}
                    <td colspan="5">UK Donor - no samples collected</td>
                {% else %}
                    {% for sample in donor.person.bloodsample_set.all %}
                {% if not forloop.first %}<tr>{% endif %}
                    <td>{{ sample.event.get_name_display }} ({{ sample.get_blood_type_display }})</td>
                    <td>{{ sample.event.taken_at }}</td>

                    <td>{{ sample.barcode|default:"Not recorded" }}</td>
                    <td class="{{ sample.collected|yesno:"bg-success,bg-danger,bg-warning" }}">
                        {{ sample.collected|yesno:"yes,no,not recorded"|capfirst }}
                    </td>
                    <td><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-xs"><i
                                title="edit" class="glyphicon glyphicon-edit"></i> {{ sample.event.id }}</a></td>
                </tr>
                    {% endfor %}
                    {% for sample in donor.person.urinesample_set.all %}
                <tr>
                    <td>{{ sample.event.get_name_display }}</td>
                    <td>{{ sample.event.taken_at }}</td>

                    <td>{{ sample.barcode|default:"Not recorded" }}</td>
                    <td class="{{ sample.collected|yesno:"bg-success,bg-danger,bg-warning" }}">
                        {{ sample.collected|yesno:"yes,no,not recorded"|capfirst }}
                    </td>
                    <td><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-xs"><i
                                title="edit" class="glyphicon glyphicon-edit"></i> {{ sample.event.id }}</a></td>
                {% if not forloop.last %}</tr>{% endif %}
                    {% endfor %}
                    {% endif %}
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>

        {% include 'includes/paginator.html' %}

    {% else %}
        <p>No events are available.</p>
    {% endif %}
{% endblock %}

wp4/theme/templates/samples/recipient_list.html
{% extends "base_site.html" %}
{% load l10n i18n %}

{% block page_title %}Samples{% endblock %}
{% block page_header %}Samples - Recipients{% endblock %}
{% block page_trail %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'wp4:index' %}">WP4: Compare</a></li>
    <li><a href="{% url 'wp4:samples:index' %}">Samples</a></li>
    <li class="active">Recipient Samples</li>
{% endblock %}

{% block content %}
    {% if recipient_list %}
        {% include 'includes/paginator.html' %}
        <table class="table table-responsive table-condensed">
            <thead>
            <tr>
                <th>Trial ID {% include 'includes/sort_column.html' with sort_by_field='trial_id' %}</th>
                <th>Name</th>
                <th>Taken at</th>
                <th>Barcode</th>
                <th>Collected</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for recipient in recipient_list %}
                <tr>
                {% with blood_count=recipient.person.bloodsample_set.all.count urine_count=recipient.person.urinesample_set.all.count %}
                    <td rowspan="{{ blood_count|add:urine_count }}">

                        <strong>{{ recipient.trial_id }}</strong><br>
                        {% if perms.samples.change_event %}
                            <a href="{% url 'wp4:samples:recipient_detail' pk=recipient.pk %}" class="btn btn-default btn-xs"><i
                                    title="edit" class="glyphicon glyphicon-eye-open"></i></a>
{#                            <a href="{% url 'wp4:samples:recipient_update' pk=event.pk %}" class="btn btn-primary btn-xs"><i#}
{#                                    title="edit" class="glyphicon glyphicon-edit"></i> {{ recipient.id }}</a>#}
                        {% elif perms.samples.view_event %}
                            <a href="{% url 'wp4:samples:recipient_detail' pk=recipient.pk %}" class="btn btn-default btn-xs"><i
                                    title="edit" class="glyphicon glyphicon-eye-open"></i> {{ recipient.id }}</a>
                        {% endif %}
                    </td>
                {% if blood_count == 0 and urine_count == 0 %}
                    <td colspan="5">No samples collected</td>
                {% else %}
                    {% for sample in recipient.person.bloodsample_set.all %}
                {% if not forloop.first %}<tr>{% endif %}
                    <td>{{ sample.event.get_name_display }} ({{ sample.get_blood_type_display }})</td>
                    <td>{{ sample.event.taken_at }}</td>

                    <td>{{ sample.barcode|default:"Not recorded" }}</td>
                    <td class="{{ sample.collected|yesno:"bg-success,bg-danger,bg-warning" }}">
                        {{ sample.collected|yesno:"yes,no,not recorded"|capfirst }}
                    </td>
                    <td><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-xs"><i
                                title="edit" class="glyphicon glyphicon-edit"></i> {{ sample.event.id }}</a></td>
                </tr>
                    {% endfor %}
                    {% for sample in recipient.person.urinesample_set.all %}
                <tr>
                    <td>{{ sample.event.get_name_display }}</td>
                    <td>{{ sample.event.taken_at }}</td>

                    <td>{{ sample.barcode|default:"Not recorded" }}</td>
                    <td class="{{ sample.collected|yesno:"bg-success,bg-danger,bg-warning" }}">
                        {{ sample.collected|yesno:"yes,no,not recorded"|capfirst }}
                    </td>
                    <td><a href="{% url 'wp4:samples:event_update' pk=sample.event.pk %}" class="btn btn-primary btn-xs"><i
                                title="edit" class="glyphicon glyphicon-edit"></i> {{ sample.event.id }}</a></td>
                {% if not forloop.last %}</tr>{% endif %}
                    {% endfor %}
                    {% endif %}
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>

        {% include 'includes/paginator.html' %}

    {% else %}
        <p>No events are available.</p>
    {% endif %}
{% endblock %}