wp4/administration/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url
from django.urls import path

from .views import core, data_extracts, administrator, completeness, dmc_reports, biobank

app_name = "administration"
urlpatterns = [
    # =================================================================  Data Extracts (aka: Statisticians' Reports)
    path(
        'stats/reports/data-simplified',
        view=data_extracts.report_data_flattened,
        name='stats_simple'
    ),
    path(
        'stats/reports/procurement',
        view=data_extracts.report_procurement,
        name='stats_p'
    ),
    path(
        'stats/reports/organs',
        view=data_extracts.report_organ,
        name='stats_o'
    ),
    path(
        'stats/reports/allocations',
        view=data_extracts.report_allocations,
        name='stats_a'
    ),
    path(
        'stats/reports/adverse-events',
        view=data_extracts.report_adverse_events,
        name='stats_ae'
    ),


    # =================================================================  Administrator Reports
    url(
        regex=r'^europe-list$',
        view=administrator.offline_europe_list,
        name='europe_list'
    ),
    url(
        regex=r'^uk-list$',
        view=administrator.offline_uk_list,
        name='uk_list'
    ),

    url(
        regex=r'^procurement-pairs$',
        view=administrator.procurement_pairs,
        name='procurement_pairs'
    ),
    url(
        regex=r'^transplantation-sites$',
        view=administrator.transplantation_sites,
        name='transplantation_sites'
    ),

    url(
        regex=r'^sae-sites$',
        view=administrator.sae_sites,
        name='sae_sites'
    ),
    url(
        regex=r'^flowchart',
        view=administrator.flowchart,
        name='flowchart'
    ),
    url(
        regex=r'^completed-pairs',
        view=administrator.completed_pairs,
        name='completed_pairs'
    ),
    url(
        regex=r'^followups',
        view=administrator.followups,
        name='followups'
    ),

    url(
        regex=r'^demographics/data-linkage$',
        view=administrator.demographics_data_linkage,
        name='demographics_data_linkage'
    ),


    # =================================================================  Completeness Reports
    path(
        'completeness/procurement/',
        view=completeness.procurement,
        name='completeness_procurement'
    ),
    path(
        'completeness/transplant-per-centre/',
        view=completeness.transplant_per_centre,
        name='completeness_tpc'
    ),
    path(
        'completeness/donor-summary/<int:donor_pk>/',
        view=completeness.donor_summary_by_donor_id,
        name='donor_summary_donor'
    ),
    path(
        'completeness/donor-summary/<str:trial_id>/',
        view=completeness.donor_summary_by_trial_id,
        name='donor_summary_trial'
    ),
    path(
        'completeness/donor-summary/',
        view=completeness.donor_summary_listing,
        name='donor_summary'
    ),
    path(
        'completeness/consent-summary/',
        view=completeness.consent_summary_listing,
        name='consent_summary'
    ),
    # Added for #336 to handle data entry
    path(
        'completeness/post-trial/<int:organ_pk>/',
        view=completeness.post_trial_categorisation_form,
        name='completeness_post_trial_form'
    ),
    path(
        'completeness/post-trial/',
        view=completeness.post_trial_categorisation_list,
        name='completeness_post_trial_list'
    ),

    # =================================================================  Biobank reports
    url(
        regex=r'^biobank/blood-collection',
        view=biobank.blood_collection,
        name='biobank_blood_collection'
    ),
    url(
        regex=r'^biobank/urine-collection',
        view=biobank.urine_collection,
        name='biobank_urine_collection'
    ),
    url(
        regex=r'^biobank/tissue-collection',
        view=biobank.tissue_collection,
        name='biobank_tissue_collection'
    ),
    url(
        regex=r'^biobank/perfusate-collection',
        view=biobank.perfusate_collection,
        name='biobank_perfusate_collection'
    ),
    url(
        regex=r'^biobank/unmatched-samples',
        view=biobank.unmatched_samples,
        name='biobank_unmatched_samples'
    ),
    url(
        regex=r'^biobank/paired-biopsies',
        view=biobank.paired_biopsies,
        name='biobank_paired_biopsies'
    ),
    url(
        regex=r'biobank/wp7-upload',
        view=biobank.wp7_file_form,
        name='biobank_wp7_form'
    ),
    url(
        regex=r'biobank/wp7-download',
        view=biobank.export_for_wp7,
        name='biobank_wp7_export'
    ),

    # =================================================================  DMC Reports
    url(
        regex=r'^dmc/death-summaries/open',
        view=dmc_reports.death_summaries,
        name='dmc_death_summaries_open',
        kwargs=dict(open_report=True),
    ),
    url(
        regex=r'^dmc/death-summaries',
        view=dmc_reports.death_summaries,
        name='dmc_death_summaries'
    ),
    url(
        regex=r'^dmc/permanent-impairment/open',
        view=dmc_reports.permanent_impairment,
        name='dmc_permanent_impairment_open',
        kwargs=dict(open_report=True),
    ),
    url(
        regex=r'^dmc/permanent-impairment',
        view=dmc_reports.permanent_impairment,
        name='dmc_permanent_impairment'
    ),
    url(
        regex=r'^dmc/graft-failures/open',
        view=dmc_reports.graft_failures,
        name='dmc_graft_failures_open',
        kwargs=dict(open_report=True),
    ),
    url(
        regex=r'^dmc/graft-failures',
        view=dmc_reports.graft_failures,
        name='dmc_graft_failures'
    ),
    url(
        regex=r'^dmc/adverse-events/open',
        view=dmc_reports.adverse_events,
        name='dmc_adverse_events_open',
        kwargs=dict(open_report=True),
    ),
    url(
        regex=r'^dmc/adverse-events',
        view=dmc_reports.adverse_events,
        name='dmc_adverse_events'
    ),
    url(
        regex=r'^dmc/serious-events/open',
        view=dmc_reports.serious_events,
        name='dmc_serious_events_open',
        kwargs=dict(open_report=True),
    ),
    url(
        regex=r'^dmc/serious-events',
        view=dmc_reports.serious_events,
        name='dmc_serious_events'
    ),

    # ================================================================= Admin Home
    url(
        regex=r'^$',
        view=core.index,
        name='index'
    ),
]

wp4/urls.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

# from .perfusion_machine import urls as perfusionmachine_urls
from .health_economics import urls as health_economics_urls
from .followups import urls as followup_urls
from .adverse_event import urls as adverseevent_urls
from .staff import urls as person_urls
# from .staff_person import urls as staffperson_urls
from .locations import urls as locations_urls
from .samples import urls as samples_urls
from .compare import urls as compare_urls
from .administration import urls as administration_urls
from .views import wp4_index


app_name = "wp4"
urlpatterns = [
    url(r'^health-economics/', include(health_economics_urls)),
    url(r'^follow-up/', include(followup_urls)),
    url(r'^adverse-event/', include(adverseevent_urls)),
    url(r'^staff/', include(person_urls)),
    url(r'^location/', include(locations_urls)),
    url(r'^sample/', include(samples_urls)),
    url(r'^compare/', include(compare_urls)),
    url(r'^administration/', include(administration_urls)),

    url(
        regex=r'^$',
        view=wp4_index,
        name='index'
    )
]

wp4/staff/models.py
#!/usr/bin/python
# coding: utf-8
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _


class Person(AbstractUser):
    """
    Replacement for original StaffPerson class which was linked to User as a one-to-one via "profile" attribute.

    This represents any person that is a member of staff (medical, administrative, academic, etc) and therefore not
    a patient (see compare.Patient for that). Not all people with records here will be active users of the system

    We'll rely on Django-Reversion to capture changes to records, and thus the audit trail.
    """
    from wp4.locations.models import Hospital

    # Constants to help reference specific staff groups (auth_groups, defined by fixtures)
    PERFUSION_TECHNICIAN = 1  #: Constant for Group ID
    TRANSPLANT_COORDINATOR = 2  #: Constant for Group ID
    RESEARCH_NURSE = 3  #: Constant for Group ID
    NATIONAL_COORDINATOR = 4  #: Constant for Group ID
    CENTRAL_COORDINATOR = 5  #: Constant for Group ID
    STATISTICIAN = 6  #: Constant for Group ID
    SYSTEMS_ADMINISTRATOR = 7  #: Constant for Group ID
    LOCAL_INVESTIGATOR = 8  #: Constant for Group ID
    OTHER_PROJECT_MEMBER = 9  #: Constant for Group ID
    BIOBANK_COORDINATOR = 10  #: Constant for Group ID
    CHIEF_INVESTIGATOR = 11  #: Constant for Group ID
    PRINCIPLE_INVESTIGATOR = 12  #: Constant for Group ID
    CENTRAL_INVESTIGATOR = 13  #: Constant for Group ID
    NATIONAL_INVESTIGATOR = 14  #: Constant for Group ID
    THEATRE_CONTACT = 15  #: Constant for Group ID

    _phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )
    _my_groups = None

    telephone = models.CharField(
        verbose_name=_("SP01 telephone number"),
        validators=[_phone_regex],
        max_length=15,
        blank=True,
        null=True
    )  #: Contents validated against phone_regex ``r'^\+?1?\d{9,15}$'``
    based_at = models.ForeignKey(
        Hospital,
        on_delete=models.PROTECT,
        verbose_name=_("SP02 location"),
        blank=True, null=True,
        help_text="Link to a primary hospital location for the member of staff"
    )

    def has_group(self, group_ids=[]):
        if self._my_groups is None:
            self._my_groups = [g.id for g in self.groups.all()]
        # print("DEBUG: I am {2}, and my_group_ids={0} and group_ids={1} ({3})".format(
        #     my_group_ids, group_ids, self.get_full_name(), type(group_ids))
        # )
        if type(group_ids) in (list, tuple):
            for group in group_ids:
                if group in self._my_groups:
                    return True
        else:
            if group_ids in self._my_groups:
                return True
        # print("DEBUG: has_group returning False")
        return False

    def _is_administrator(self):
        """
        Checks for membership of an admin group
        :return:
        """
        administrator_groups = (self.NATIONAL_COORDINATOR, self.CENTRAL_COORDINATOR, self.SYSTEMS_ADMINISTRATOR,
                                self.BIOBANK_COORDINATOR, self.CHIEF_INVESTIGATOR, self.PRINCIPLE_INVESTIGATOR,
                                self.NATIONAL_INVESTIGATOR, self.CENTRAL_INVESTIGATOR, self.STATISTICIAN,)
        if self.has_group(administrator_groups):
            return True
        elif self.has_group(self.CENTRAL_INVESTIGATOR) and settings.DEBUG is True:
            # Add a pass through for Ina when on the test server as per Issue #249
            return True
        return False

    is_administrator = cached_property(_is_administrator, name='is_administrator')

    class Meta:
        verbose_name = _('SPm1 person')
        verbose_name_plural = _('SPm2 people')
        ordering = ['id']
        permissions = (
            ("single_person", "Can only view their own person record"),
        )

    def get_absolute_url(self):
        return reverse("wp4:staff:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.get_full_name()

wp4/theme/templates/includes/messages.html
{% load staticfiles l10n i18n theme_tags %}
<!-- Start: wp4/templates/includes/messages.html -->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
{#                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}#}
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}
<!-- End: wp4/templates/includes/messages.html -->

wp4/theme/templates/includes/navbar.html
{% load staticfiles l10n i18n theme_tags tz %}
<!-- Start: wp4/templates/includes/navbar.html -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">COPE DB Online Trials System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

            {# ================================================== LOGGED IN =================================================== #}
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    {% url 'home' as url_home %}
                    <li class="{% active request url_home %}" id="navbar-menu-home"><a href="{{ url_home }}">Home</a></li>

                    <li class="dropdown" id="navbar-menu-wp4">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">WP4: Compare <span class="caret"></span></a>
                        <ul class="dropdown-menu">

                            {% url 'wp4:index' as url_wp4index %}
                            <li class="{% active request url_wp4index %}"><a href="{{ url_wp4index }}">WP4 Home</a></li>
                            <li role="separator" class="divider"></li>

                            {% if perms.compare.change_donor or perms.compare.view_donor %}
                                {% url 'wp4:compare:procurement_list' as url_procurement %}
                                <li class="{% active request url_procurement %}"><a href="{{ url_procurement }}">Procurement</a></li>
                            {% endif %}

                            {% if perms.compare.change_recipient or perms.compare.view_recipient %}
                                {% url 'wp4:compare:transplantation_list' as url_transplantation %}
                                <li class="{% active request url_transplantation %}"><a href="{{ url_transplantation }}">Transplantation</a></li>
                            {% endif %}

                            {% if perms.samples.change_event or perms.samples.view_event %}
                                {% url 'wp4:samples:index' as url_samples %}
                                <li class="{% active request url_samples %}"><a href="{{ url_samples }}">Samples</a></li>
                            {% endif %}

                            {% if perms.followups.change_followupinitial or perms.followups.view_followupinitial %}
                                {% url 'wp4:follow-ups:index' as url_followup %}
                                <li class="{% active request url_followup %}"><a href="{{ url_followup }}">Follow Up</a></li>
                            {% endif %}

                            {% if perms.health_economics.change_qualityoflife or perms.health_economics.view_qualityoflife %}
                                {% url 'wp4:health-economics:index' as url_healtheconomics %}
                                <li class="{% active request url_healtheconomics %}"><a href="{{ url_healtheconomics }}">Health Economics</a></li>
                            {% endif %}

                            {% if perms.adverse_event.change_event or perms.adverse_event.view_event %}
                                {% url 'wp4:adverse-event:list' as url_adverseevents %}
                                <li class="{% active request url_adverseevents %}"><a href="{{ url_adverseevents }}">Adverse Events</a></li>
                            {% endif %}
                        </ul>
                    </li>

                    <li class="dropdown" id="navbar-menu-wp4">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Administration <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if user.is_administrator %}
                                {% url 'wp4:administration:index' as url_administration_home %}
                                <li class="{% active request url_administration_home %}"><a href="{{ url_administration_home }}">Administration Home</a></li>
                                <li role="separator" class="divider"></li>
                            {% endif %}

                            {% if perms.staff.change_person or perms.staff.single_person %}
                                {% url 'wp4:staff:list' as url_staff %}
                                <li class="{% active request url_staff %}"><a href="{{ url_staff }}">Staff</a></li>
                            {% endif %}
                        </ul>
                    </li>

                    {% if user.is_staff %}
                        {% url 'admin:index' as url_admin_home %}
                        <li id="navbar-menu-admin"><a href="{{ url_admin_home }}"><i class="glyphicon glyphicon-briefcase"></i></a></li>
                    {% endif %}

                    <li class="dropdown" id="navbar-menu-aboutme">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="glyphicon glyphicon-user"></i><span class="visible-xs-block"> About Me</span> {{ user.first_name }}
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-header">About me</li>
                            <li><a href="#">Name: {{ user.get_full_name }}</a></li>
                            <li><a href="#">Job{{ user.groups.all|pluralize }}:
                                {% for group in user.groups.all %}
                                    {{ group.name }}, {% endfor %}</a></li>
                            <li><a href="#">Username: {{ user.username }}</a></li>
                            <li><a href="#">Based at: {{ user.based_at }}</a></li>
                            {% get_current_timezone as TIME_ZONE %}
                            <li><a href="#">Timezone: {{ TIME_ZONE }}</a></li>
                            <li class="dropdown-header">Actions</li>
                            <li><a href="{% url 'password_change' %}">Change Password</a></li>
                            <li><a href="{% url 'wp4:staff:update' pk=user.id %}">Edit Profile</a></li>
                        </ul>
                    </li>

                    {#                TODO: Implement the contact us #}
                    {#                    <li><a href="#" title="Contact Us"><i class="glyphicon glyphicon-envelope"></i><span#}
                    {#                            class="visible-xs-block"> Contact Us</span></a></li>#}


                    <li class="dropdown" id="navbar-menu-language">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                           title="Language">
                            <i class="glyphicon glyphicon-globe"></i><span class="visible-xs-block"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% for lang in LANGUAGES %}
                                <li {% if lang.0 == LANGUAGE_CODE %}class="active"{% endif %}>
                                    {% with "img/locale/"|add:lang.0|add:".png" as lang_flag_url %}
                                        <a href="javascript:set_language('{{ lang.0 }}')">
                                            <img src="{% static lang_flag_url %}"> {{ lang.1|localize }}
                                        </a>
                                    {% endwith %}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li id="navbar-menu-logout"><a href="{% url 'logout' %}?next=/" title="Logout"><i
                            class="glyphicon glyphicon-off"></i><span class="visible-xs-block"> Logout</span></a></li>
                </ul>


                {# ============================================== NOT LOGGED IN =================================================== #}
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    {#                    <li><a href="#" title="Contact Us"><i class="glyphicon glyphicon-envelope"></i><span#}
                    {#                            class="visible-xs-block"> Contact Us</span></a></li>#}
                    <li class="dropdown" id="navbar-menu-language">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"
                           title="Language">
                            <i class="glyphicon glyphicon-globe"></i><span class="visible-xs-block"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% for lang in LANGUAGES %}
                                <li {% if lang.0 == LANGUAGE_CODE %}class="active"{% endif %}>
                                    {% with "img/locale/"|add:lang.0|add:".png" as lang_flag_url %}
                                        <a href="javascript:set_language('{{ lang.0 }}')"><img
                                                src="{% static lang_flag_url %}"> {{ lang.1 }}
                                            ({{ lang.0 }})</a>
                                    {% endwith %}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <a href="{% url 'login' %}" class="btn btn-default navbar-btn navbar-right">Login</a>
            {% endif %}
        </div>
    </div>
</nav>

{% if debug %}
<div class="alert alert-danger text-center" role="alert">
    <h2>THIS IS THE TEST SYSTEM - DEBUG IS ACTIVE</h2>
    <p>You can access the live system at <a href="https://cope.nds.ox.ac.uk/">https://cope.nds.ox.ac.uk/</a></p>
</div>
{% endif %}
<!-- End: wp4/templates/includes/navbar.html -->

wp4/theme/templates/includes/paginator.html
<!-- Start: /wp4/templates/includes/paginator.html -->
{% load theme_tags %}
    {% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="disabled"><a href="#" aria-label="Pages">Page</a></li>
{#            {% if page_obj.number != 1 %}#}
{#            <li>#}
{#                <a href="?page=1&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Beginning" aria-label="Beginning">#}
{#                    <i class="glyphicon glyphicon-fast-backward" aria-hidden="true"></i>#}
{#                </a>#}
{#            </li>#}
{#            {% endif %}#}
{#            {% if page_obj.has_previous %}#}
{#            <li>#}
{#                <a href="?page={{ page_obj.previous_page_number }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Previous" aria-label="Previous">#}
{#                    <i class="glyphicon glyphicon-step-backward" aria-hidden="true"></i>#}
{#                </a>#}
{#            </li>#}
{#            {% endif %}#}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li>
                        <a href="?{% query_transform request page=i %}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}

{#            {% if page_obj.has_next %}#}
{#            <li>#}
{#                <a href="?page={{ page_obj.next_page_number }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Next" aria-label="Next">#}
{#                    <i class="glyphicon glyphicon-step-forward" aria-hidden="true"></i>#}
{#                </a>#}
{#            </li>#}
{#            {% endif %}#}
{#            {% if page_obj.number != page_obj.paginator.num_pages %}#}
{#            <li>#}
{#                <a href="?page={{ page_obj.paginator.num_pages }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="End" aria-label="End">#}
{#                    <i class="glyphicon glyphicon-fast-forward" aria-hidden="true"></i>#}
{#                </a>#}
{#            </li>#}
{#            {% endif %}#}
        </ul>


{#        <ul class="pager">#}
{#            {% if page_obj.number != 1 %}#}
{#            <li><a href="?page=1&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Beginning"><i class="glyphicon glyphicon-fast-backward"></i></a></li>#}
{#            {% endif %}#}
{#            {% if page_obj.has_previous %}#}
{#            <li><a href="?page={{ page_obj.previous_page_number }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Previous"><i class="glyphicon glyphicon-step-backward"></i></a></li>#}
{#            {% endif %}#}
{##}
{#            <li>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>#}
{##}
{#            {% if page_obj.has_next %}#}
{#            <li><a href="?page={{ page_obj.next_page_number }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="Next"><i class="glyphicon glyphicon-step-forward"></i></a></li>#}
{#            {% endif %}#}
{##}
{#            {% if page_obj.number != page_obj.paginator.num_pages %}#}
{#            <li><a href="?page={{ page_obj.paginator.num_pages }}&order_by={{ request.GET.order_by }}&ordering={{ request.GET.ordering }}" title="End"><i class="glyphicon glyphicon-fast-forward"></i></a></li>#}
{#            {% endif %}#}
{#        </ul>#}
    </nav>
    {% endif %}
<!-- End: /wp4/templates/includes/paginator.html -->

wp4/theme/templates/includes/sort_column.html
{% load theme_tags %}
<!-- Start wp4/templates/includes/sort_column.html -->
{% if request.GET.order_by == sort_by_field and request.GET.ordering == "asc" or request.GET.order_by == none and default_sort|default:False %}
    <a href="?{% query_transform request order_by=sort_by_field ordering='desc' %}">
        <i class="text-success glyphicon glyphicon glyphicon-sort-by-attributes"></i>
    </a>
{% elif request.GET.order_by == sort_by_field and request.GET.ordering == "desc" %}
    <a href="?{% query_transform request order_by=None ordering=None %}">
        <i class="text-success glyphicon glyphicon glyphicon-sort-by-attributes-alt"></i>
    </a>
{% else %}
    <a href="?{% query_transform request order_by=sort_by_field ordering='asc' %}">
        <i class="glyphicon glyphicon glyphicon-sort"></i>
    </a>
{% endif %}
<!-- End wp4/templates/includes/sort_column.html -->